//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.11

pub use super::heart_rate_datas::Entity as HeartRateDatas;
pub use super::sleep_datas::Entity as SleepDatas;
pub use super::users::Entity as Users;
